### ISSUE TITLE
suggest changes to content/structure

### ISSUE THREAD

**Issue by jaktk** [Global-Health-Engineering/pre-cleaning-system-design-for-HDPE-bottles#2]
Hi Lars, this repo is there to share Timo's hardware design. I started putting together its conent. If you have any suggestions, please suggest or commit them into a branch.

Together with Nic, we figured out it does not make too much sense in using the Open Hardware license as it is quite specific to electronic harware design. I would just go with our standard CC-BY-4.0.

**Comment by larnsce** [comment]
Thank you, @jaktk. This is exciting. Thank you for doing the research on licensing, good to know that CCBY works.

On content and structure:

- Keep the landing README.md short and to the point, if you write up a more comprehensive handbook, do that separately and link it
- Have a look if you can find other examples of best practices for setting up open source repositories for hardware. Have you seen this? https://github.com/aolofsson/awesome-opensource-hardware  (more details: https://www.perplexity.ai/search/What-are-best-eYt395oZQu.ZcB15YuS_Jw#1)

On archiving and citation.

- Use the Zenodo GitHub integration for archiving on Zenodo and DOI generation. I would say that's the most important part. 
- Then add the DOI to your CITATION.cff
- Once you are done, import the entry using the DOI to the ETH Research Collection

Addition to our GHE website:

- we will need a new category "Designs" under "Publications" https://ghe.ethz.ch/publications.html

**Comment by jaktk** [comment]
Thanks @larnsce, I've seen those repos, at least part of them. My problem with them is that they are very electronics-focused (where actually OHRW license would be a good option).

There is an open sprinkler project: https://github.com/OpenSprinkler where they cover both software and hardware (limited to cad drawings). However, the hardware part of this repo is much less developed compared to the software version and I somehow understand it - these are just the cad files.

To sumarize, I haven't found something very very relevant which would change my view on it. One example which I like (from NASA) is here: https://github.com/nasa-jpl/open-source-rover . But again, that's a repo where hardware development (i.e., frame, wheels) is important of less importance compared to electronics.

Regarding the README structure, do you have an example? I was used to writing everything in the main readme actually, sort of like with one of your repos: https://github.com/Global-Health-Engineering/durbanplasticwaste

Regarding citations, that's pretty clear. The only point which we should discuss is whether this should be imported as a seprarate entry to the ETH research collection or rather a supplementary information to the manuscript, just like in case of Dominic Waltti's work: https://www.research-collection.ethz.ch/handle/20.500.11850/646138

**Comment by larnsce** [comment]
> The only point which we should discuss is whether this should be imported as a seprarate entry to the ETH research collection or rather a supplementary information to the manuscript

As a separate entry. Then, still add it as supplementary information anyways. It will increase it's discoverability a lot by being a separate entry. I would also suggest to do that for students going forward.

**Comment by jaktk** [comment]
Thanks, Lars.
